# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restroom_id', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restroom_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('review_text', models.CharField(max_length=500)),
                ('review_num', models.IntegerField()),
            ],
        ),
    ]
