# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restrooms',
            new_name='restroom',
        ),
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2017, 12, 12, 18, 31, 38, 718216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_num',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
