# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom', '0002_auto_20171212_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
