# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom', '0003_auto_20171212_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroom',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='restroom',
            name='lng',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
