# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom', '0005_auto_20171216_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_num',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
